

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    
    <!-- Title Tag -->
    <title>Emergences</title>
<!--

November Template

http://www.templatemo.com/tm-473-november

-->
    <!-- <<Mobile Viewport Code>> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
            
    <!-- <<Attched Stylesheets>> -->
    <link rel="stylesheet" href="css/theme.css" type="text/css" />
    <link rel="stylesheet" href="css/media.css" type="text/css" />
    <link rel="stylesheet" href="css/font-awesome.min.css" type="text/css" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,600italic,400italic,800,700' rel='stylesheet' type='text/css'>    
    <link href='https://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>

</head>
<body>

<!-- \\ Begin Holder \\ -->
<div class="DesignHolder">
	<!-- \\ Begin Frame \\ -->
	<div class="LayoutFrame">
        <!-- \\ Begin Header \\ -->
        <header>
            <div class="Center">
                <div class="site-logo">
                	<h1><a href="#">Emer<span>gen</span>ces</a></h1>
                </div>
               <div id="mobile_sec">
               <div class="mobile"><i class="fa fa-bars"></i><i class="fa fa-times"></i></div>
                <div class="menumobile">
                    <!-- \\ Begin Navigation \\ -->
                    <nav class="Navigation">
                        <ul>
                            <li class="active">                                
                                <a href="#home">Home</a>
                                <span class="menu-item-bg"></span>
                            </li>
                            <li>
                                <a href="#about">Chi siamo</a>
                                <span class="menu-item-bg"></span>
                            </li>
                            <li>
                                <a href="#services">Servizi</a>
                                <span class="menu-item-bg"></span>
                            </li>
                            <li>
                                <a href="#pricing">FAQ</a>
                                <span class="menu-item-bg"></span>
                            </li>
                            <li>
                                <a href="#contact">Contattaci</a>
                                <span class="menu-item-bg"></span>
                            </li>
                        </ul>
                    </nav>
                    <!-- // End Navigation // -->
				</div>
				</div>
                <div class="clear"></div>
            </div>
        </header>
        <!-- // End Header // -->
        <!-- \\ Begin Banner Section \\ -->
        <div class="Banner_sec" id="home">
            <!--  \\ Begin banner Side -->
            <div class="bannerside">
	            <div class="Center">
                    <!--  \\ Begin Left Side -->
                    <div class="leftside">
                        <h3>Sicurezza sul territorio<span>Gestione delle emergenze</span></h3>
                        <p>Emergences è un sito che si occupa della gestione delle emergenze e l'attivazione di procedure di sicurezza. </p>
                        <a href="#about">SCOPRI DI PIU'</a>
                    </div>                        								
                    <!--  // End Left Side // -->
                    <!--  \\ Begin Right Side -->
                    <div class="rightside">
                    	<ul id="slider">	
                    		<li>
                                <div class="Slider">
                                    <figure><img src="img/Univpm-Villarey_interno.jpg" width="1000" height="400" alt="image"></figure>
                                    <div class="text">                       								
                                        <div class="Lorem">
                                            <p>Univpm	<span>Facoltà di economia </span></p>
                                        </div>
                                    </div>
                                </div>
							</li>
                    		<li>
                                <div class="Slider">
                                    <figure><img src="img/873894-Ospedale_Torrette.JPG" width="1000" height="400" alt="image"></figure>
                                    <div class="text">                     								
                                        <div class="Lorem">
                                            <p>Ancona	<span>Ospedale Torrette</span></p>
                                        </div>
                                    </div>
                                </div>
							</li>
						</ul>                                                            
            	        <figure><img src="img/Shadow-img.png" alt="image" class="Shadow"></figure>                                                        
                    </div>
                    <!--  // End Right Side // -->
	            </div>
            </div>
            <!--  // End banner Side // -->
            <div class="clear"></div>
        </div>
        <!-- // End Banner Section // -->
         <div class="bgcolor"></div>
        <!-- \\ Begin Container \\ -->
        <div id="Container">
            <!-- \\ Begin About Section \\ -->
<?php echo $this->layout()->content; ?>           
                <!-- // End Pricing Side // -->
            </div>
        </div>
        <!-- // End Pricing Section // -->
        <!-- \\ Begin Contact Section \\ -->
        <div class="Contact_sec" id="contact">
            <div class="Contactside">
                <div class="Center">
                    <h4>CONTATTACI</h4>
      
                    <div class="Line"></div> 
                     <p>                                <address>
                                    990 Proin Gravida Street, Aliquet Snean Tate,<br>Lincoln Way, San Francisco, California.
                                </address>	
                                <address class="Number">
                                    (+001) 001 002 0034, (+002) 009 008 0760<br>(+003) 456 050 0670 
                                </address>	
                                <address class="Email">
                                    <a href="mailto:info@november.com">info@emergences.com</a>
                                </address></p>
                </div>  

            </div>

                    <!-- \\ Begin Footer \\-->
                    <footer>
                        <div class="Cntr">                
                            <p>COPYRIGHT © 2016 PROGETTO CORSO TECNOLOGIE WEB </p>
                        </div>
                    </footer>
                    <!-- // End Footer // -->
                </div>
                <!-- // End Get Section // -->
            
            </div>
            <!-- // End Contact Section // -->
        </div>
        <!-- // End Container // -->
	</div>
	<!-- // End Layout Frame // -->
</div>
<!-- // End Design Holder // -->
<div id="loader-wrapper">
<div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>

</div>

<!-- <<Attched Javascripts>> -->
<script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="js/jquery.sudoSlider.min.js"></script>
<script type="text/javascript" src="js/global.js"></script>
<script type="text/javascript" src="js/modernizr.js"></script>

</body>
</html>